security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory:
            memory:
                users:
                    token: {}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:  ^/api/
            security: true
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

        mz:
            pattern:  ^/api\/article\/list/
            security: false
            anonymous: true
            stateless: true
