security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory:
            memory:
                users:
                    token: {}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        doc:
            pattern: ^/api/doc
            security: false

        public:
            pattern:  ^/api/article/list
            security: false
            anonymous: true
            stateless: true

        private:
            pattern:  ^/api/
            security: true
            anonymous: false
            stateless: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
